Add in config option for NewRelicQuerySupplier.
newrelic-forks/cruise-control pull request #15
Opened 2021-07-29 22:51 UTC by preethamsura

Created a NewRelicQuerySupplier interface with the current query supplier being used becoming the DefaultNewRelicQuerySupplier. Added the option to input a different query supplier into the config if needed as long as that config implements NewRelicQuerySupplier. 

This should make it easier for anyone who isn't using the exact same naming conventions as us to use the NewRelicMetricSampler because it will allow them to create their own NewRelicQuerySupplier. 

Finally I also just added tests to make sure that the configuration was working properly and that we stick to the default when it isn't passed in.

2021-07-30 17:50 UTC, jlei-nr requested changes
I think we should look into the `public static final Map` w/ immutable maps thing and adding some Javadocs but looks good overall!

2021-07-30 17:50 UTC, jlei-nr commented on cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/newrelic/NewRelicQuerySupplier.java
> +public interface NewRelicQuerySupplier {
Javadocs plz

2021-07-30 17:50 UTC, jlei-nr commented on cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/newrelic/DefaultNewRelicQuerySupplier.java
> +    private static final HashMap<String, RawMetricType> PARTITION_METRICS = new HashMap<>();
I think these can be instance variables

2021-07-30 17:50 UTC, jlei-nr commented on cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/newrelic/DefaultNewRelicQuerySupplier.java
> +    public String brokerQuery(String clusterName) {
`@Override` annotations

2021-07-30 17:50 UTC, jlei-nr commented on cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/newrelic/DefaultNewRelicQuerySupplier.java
> +    private static final HashMap<String, RawMetricType> PARTITION_METRICS = new HashMap<>();
NVM these should be static - you were correct

2021-07-30 17:50 UTC, jlei-nr commented on cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/newrelic/DefaultNewRelicQuerySupplier.java
> +    private static final HashMap<String, RawMetricType> PARTITION_METRICS = new HashMap<>();
We should check if there's some sort of ImmutableMap available that we can use here

2021-07-30 17:50 UTC, jlei-nr commented on cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/newrelic/DefaultNewRelicQuerySupplier.java
> +    private static final HashMap<String, RawMetricType> PARTITION_METRICS = new HashMap<>();
If yes, we can definitely just make these `public static final`

2021-08-02 08:32 UTC, preethamsura commented on cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/newrelic/DefaultNewRelicQuerySupplier.java
> +    private static final HashMap<String, RawMetricType> PARTITION_METRICS = new HashMap<>();
So I didn't make it public static final (because static variables and implements are weird), but I did make it so that the getters for these maps all return an unmodifiable version of the maps because that makes sure that no one else can modify these maps

2021-08-17 21:06 UTC, jlei-nr approved these changes

2021-08-17 23:35 UTC, merged